# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Reussite

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: docker-container

jobs:

  push_to_registry:
  
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build docker image
        run: docker build -t secrets.TEMPREGISTRE/${{env.DOCKER_IMAGE_NAME}}:latest .
        
      - name: Push docker image
        run: docker push secrets.TEMPREGISTRE/${{env.DOCKER_IMAGE_NAME}}:latest
